## Assignment 7

# Create a Vagrantfile that provisions a VM with Ruby installed and runs a script.
Vagrant.configure("2") do |config| 
    config.vm.box = "ubuntu/focal64"
    config.vm.provider "virtualbox" do |vb| 
        vb.memory = "2048"
        vb.cpus = "2"
    end
    config.vm.provision "file", source: "index.rb", destination: "/tmp/index.rb"
    config.vm.provision "shell", inline: <<-SHELL 
        sudo apt-get update
        sudo apt-get install -y ruby-full
    SHELL
end