## Assignment 4

# Create a Vagrantfile that provisions a VM with MongoDB installed and creates a database and a user.
Vagrant.configure("2") do |config| 
    config.vm.box = "ubuntu/focal64"
    config.vm.define "MongoDB"
    config.vm.hostname = "ubuntu-mongo"
    config.vm.provision "shell", path: "mongo-init.sh"
    config.vm.provider "virtualbox" do |vb| 
        vb.memory = "4096"
        vb.cpus = "4"
        vb.disksize.size = "40GB"
    end
    
end