## Assignment 9

# Create a Vagrantfile that provisions a VM with Ansible installed and runs a playbook.
Vagrant.configure("2") do |config| 
    config.vm.box = "ubuntu/focal64"
    
    config.vm.provider "virtualbox" do |vb| 
      vb.memory = "2048"
      vb.cpus = "2"
    end
    
    config.vm.provision "ansible" do |ansible| 
      ansible.playbook = "playbook.yml"
    end
    #Forward port 80 to 8080
    config.vm.network "forwarded_port", guest: 80, host: 8080
  end
  